from views.tab_visao_geral import render_tab_visao_geral
from views.tab_visualizar_dados import render_tab_visualizar_dados
from views.tab_performance import render_tab_performance
from views.tab_analise_ia import render_tab_analise_ia
from views.tab_classificador import render_tab_classificador
from views.tab_mom import render_tab_mom
from views.tab_yoy import render_tab_yoy
from views.tab_dados_colados import render_tab_dados_colados
